name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: pip install uv && uv sync
      - name: format
        run: uv run black classes/*.py
      - name: lint
        run: uv run python -m pylint classes/*.py
      - name: test
        run: uv run pytest tests/ -vv --cov=classes --cov-config=pyproject.toml
      - name: doc
        run: uv run pdoc3 --html classes --output-dir docs/classes --force
      - name: Commit docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/classes
          git commit -m "Update docs"
          git push origin master
